app/models/Employees.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;	
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use yii\web\IdentityInterface;
use yii\web\UploadedFile;
use yii\base\Model;
/**
 * This is the model class for table "employees".
 *
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property integer $role
 * @property integer $Percent_of_jobs
 * @property integer $cellphone
 * @property string $adress
 * @property string $armed
 *
 * @property Role $role0
 */
class Employees extends \yii\db\ActiveRecord
{
    
	
	
	public static function tableName()
    {
        return 'employees';
    }
/**
* access url
**/
	
	
	  
	
	
 
	
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'first_name', 'last_name', 'role', 'Percent_of_jobs', 'cellphone', 'adress', 'armed'], 'required','message'=>'שדה חובה'],
            [['id', 'role', 'Percent_of_jobs', 'created_at','updated_at','created_by','updated_by'], 'integer','message'=>'ספרות בלבד'],
			['email', 'email'],
			[['image'],'file'],
			[['files'],'file'],
            [['first_name', 'last_name', 'adress', 'armed','image','cellphone','color'], 'string', 'max' => 255],
            
        ];
    }
	
	
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ת.ז',
            'first_name' => 'שם פרטי',
            'last_name' => 'שם משפחה',
            'role' => 'תפקיד',
            'Percent_of_jobs' => 'אחוזי משרה',
            'cellphone' => 'טלפון',
            'adress' => 'כתובת',
			'email'  => 'מייל',
            'armed' => 'נשק',
			'image' => 'תמונה',
			'color' => 'צבע',
			'files' => 'קבצי עובד',
			'created_at' => 'created_at',
			'updated_at' => 'updated_at',
			'created_by' => 'created_by',
			'updated_by' => 'updated_by',
        ];
    }
	
	public function behaviors()
    {
		return 
		[
			[
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'created_by',
				'updatedByAttribute' => 'updated_by',
			 ],
				'timestamp' => [
				'class' => 'yii\behaviors\TimestampBehavior',
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
				],
			],
		];
    }
	
	public function getColor()
    {
        return $this->color;
    }
	
	public static function getEmail()
    {
       return $this->email;		
    }
	
	public function getFullname()
    {
        return $this->first_name.' '.$this->last_name;
    }
	
	public function getId()
    {
        return $this->id;
    }
	
	public static function getEmployees() //function that give employee's names
	{
		$allEmployees = self::find()->all();
		$allEmployeesArray = ArrayHelper::
					map($allEmployees, 'id', 'fullname');
		return $allEmployeesArray;						
	}
	
	public static function getEmployeesID($fullname) //function that give employee's names
	{
		$arrfullname = explode(' ',$fullname);
		$IDEmployees = self::find()->where(['first_name' => "$arrfullname[0]",'last_name'=>"$arrfullname[1]"])->one();
		
		return  $IDEmployees->id;						
	}
	
	public static function getEmployeesPerDays($employeesForDay)
	{
		$allEmployees = self::find()->where(['id' => $employeesForDay])->all();
		
		$allEmployeesArray = ArrayHelper::
					map($allEmployees,'id' , 'fullname');
		return $allEmployeesArray;						
	}

	public static function getTeamLeaderTprojects($id) //send fullname of team_leade to project
	{
		$ProjectTeamLeader = self::find()->where(['id' => $id])->one();
		
		  return $ProjectTeamLeader->fullname;
	}
	
	
	public static function getEmployeesToUsers($employeesForDay)
	{
		$allEmployees = self::find()->where(['id' => $employeesForDay])->all();
		
		$allEmployeesArray = ArrayHelper::
					map($allEmployees,'id' , 'fullname');
		return $allEmployeesArray;						
	}
	
	public static function getEmployeesEmails() //function that give all employee's email
	{
		$allEmployees = self::find()->all();
		$allEmployeesArray = ArrayHelper::
					map($allEmployees, 'id', 'email');
		return $allEmployeesArray;						
	}
	
	public static function getEmployeesEmailsToProjects($id) //send email employee to project
	{
	$allEmployees = self::find()->where(['id' => $id])->all();
		$allEmployeesArray = ArrayHelper::
					map($allEmployees, 'id', 'email');
		return $allEmployeesArray;						
	}
	
	public function getfile()
    {
        return $this->hasMany(ImageManager::className(), ['item_id' => 'id']);
    }

	
	
	public function getRoleItem()
    {
        return $this->hasOne(Role::className(), ['id' => 'role']);
    }
	
	public function getArmedItem()
    {
        return $this->hasOne(Armed::className(), ['id' => 'armed']);
    }
	
	public function getPercent_of_jobsItem()
    {
        return $this->hasOne(PercentOfJobs::className(), ['id' => 'Percent_of_jobs']);
    }
	
	public function getUserItem()
    {
        return $this->hasMany(User::className(), ['id' => 'id']);
    }

	public function getProjectEmployee()
    {
        return $this->hasMany(Projects::className(), ['employee' => 'id']);
    }
    
	public function getProjectTeamleder()
    {
        return $this->hasOne(Projects::className(), ['team_leade' => 'id']);
    }


public static function getEproject()
	{
		$allEproject = self::find()->all();
		$allEprojectArray = ArrayHelper::
					map($allEproject, 'id', 'fullname');
		return $allEprojectArray;						
	}
	
	public static function getEprojectWithAllEproject()
	{
		$allEproject= self::getEproject();
		$allEproject[-1] = 'כל סוגי הנשק';
		$allEproject = array_reverse ( $allEproject, true );
		return $allEproject;	
	}		

	}

app/controllers/EmployeesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employees;
use app\models\EmployeesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Role;
use app\models\Armed;
use app\models\ImageManager;
use app\models\PercentOfJobs;
use yii\web\UnauthorizedHttpException;
use yii\filters\AccessControle;
use yii\web\UploadedFile;
use app\models\UploadForm;
use dosamigos\fileupload\FileUpload;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
         return [
			'access'=>[
			     'class'=>\yii\filters\AccessControl::className(),
				 'only'=>['create','update','index','view','delete'],
				 'rules'=>[
				    [
						'allow'=>true,
						'roles'=>['@']
					],			 
				 ]	
			],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	
	
    /**
     * Lists all Employees models.
     * @return mixed
     */
    public function actionIndex()
    {
        
		if (!\Yii::$app->user->can('indexEmployee'))
			throw new UnauthorizedHttpException ('שלום, אתה לא מורשה לבצע פעולה זו!');
		
		$searchModel = new EmployeesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'roles' => Role::getRolesWithAllRoles(),
			'role' => $searchModel->role,
			'armeds' => Armed::getArmedsWithAllArmeds(),
			'armed' => $searchModel->armed,
			'PercentOfJobss' => PercentOfJobs::getPercentOfJobssWithAllPercentOfJobss(),
			'Percent_of_jobs' => $searchModel->Percent_of_jobs,
		
        ]);
    }

    /**
     * Displays a single Employees model.
     * @param integer $id
     * @return mixed
     */
	 
	 
	 public function actionExport()
    {
		$employeeExport= Employees::find()->all();
		\moonland\phpexcel\Excel::widget([
			'models' => $employeeExport,
			'mode' => 'export', //default value as 'export'
			'columns' => ['id','first_name','last_name','cellphone','adress','role','armed','Percent_of_jobs','email'], //without header working, because the header will be get label from attribute label. 
			'headers' => ['id' => 'ת.ז', 'first_name' => 'שם פרטי','last_name' => 'שם משפחה', 'cellphone' => 'פלאפון', 'adress' => 'כתובת', 'role' => 'תפקיד', 'armed' => 'סוג נשק','Percent_of_jobs' =>'אחוז משרה','email'=>'מייל'], 
			'fileName' => 'Employees',
	
		]);
	}
	 
    public function actionView($id)
    {
		if (!\Yii::$app->user->can('viewEmployee'))
			throw new UnauthorizedHttpException ('שלום, אתה לא מורשה לבצע פעולה זו!');
		
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
	
	public function actionFiles($id)
    {
		
        return $this->render('files', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employees model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
       

		if (!\Yii::$app->user->can('createEmployee'))
			throw new UnauthorizedHttpException ('שלום, אתה לא מורשה לבצע פעולה זו!');
		$model = new Employees();

        if ($model->load(Yii::$app->request->post())) 
		{
			$model->save();
			
				$employeeId = $model->id;
				$image= UploadedFile::getInstance($model, 'image'); //מקבל מופע של העלאת התמונה
				$imgName = 'employee_' . $employeeId . '.' . $image->getExtension();
				$image->saveAs('Employees_images/' .$imgName);
				$model->image = $imgName;
				$model->save();
			
			
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Employees model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
	
	
        $model = $this->findModel($id);
		if (!\Yii::$app->user->can('updateEmployee'))
			throw new UnauthorizedHttpException ('שלום, אתה לא מורשה לבצע פעולה זו!');
        if ($model->load(Yii::$app->request->post()) ) 
		{
			
			$employeeId = $model->id;
			$image= UploadedFile::getInstance($model, 'image'); //מקבל מופע של העלאת התמונה
			$imgName = 'employee_' . $employeeId . '.' . $image->getExtension();
			$image->saveAs('Employees_images/' .$imgName);
			$model->image = $imgName;
			$model->save();
			
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Employees model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
	
		if (!\Yii::$app->user->can('deleteEmployee'))
			throw new UnauthorizedHttpException ('שלום, אתה לא מורשה לבצע פעולה זו!');
	
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
	public function actionUploadFiles() //העלאת קבצים (לא תמונה)
	{	
		//$TestModel = \app\models\ImageManager::find()->all();
		if(Yii::$app->request->isPost){
			$post = Yii::$app->request->post();
			$dir =  'Employees_files/';
			if(!file_exists($dir)){
				FileHelper::createDirectory($dir);
			}
			$result_link = 'Employees_files/';
			$model= new ImageManager();
			$file = UploadedFile:: getInstanceByName('ImageManager[attachment]');
			//$file= UploadedFile::getInstance($model, 'attachment'); //מקבל מופע של העלאת התמונה
			
			//$model->name = 'attachment_number'.'_'.Yii::$app->getSecurity()->generateRandomString(6) .;
			//$model->name = "test1.pdf";
				$model->save();
			$model->load($post);
			$model->validate();
			if($model->hasErrors()){
				$result =[
					'error' => $model->getFirstError('file')
				];
			}else{
				if($file->saveAs($dir . $model->name)){
				  // $imag = Yii::$app->file->load($dir . $model->name);
				   //$imag->resize(800,NULL,Yii\image\drivers\Image::PRECISE)->save($dir . $model->name, 85);
				   $result = ['filelink' => $result_link . $model->name, 'filename'=>$model->name];
				}else{
					$result =[
					   'error' => 'טעות'
					];
					
				}
				$model->save();
			}
			Yii::$app->response->format = Response::FORMAT_JSON;
			return $result;	
		}else{
			throw new BadRequestHttpException('רק פוסט מותר ');
		}
	
	
	}
	
	
	
	
	
	
	
	
    /**
     * Finds the Employees model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employees the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employees::findOne($id)) !== null) {
           
			return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	
	
	
	
	
	
	
	
}

app/views/employees/_form.php
<?php
use kartik\color\ColorInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Employees;
use app\models\Role;
use app\models\Armed;
use app\models\PercentOfJobs;
use app\models\User;
use kartik\file\FileInput;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->input('email') ?>
	
	<?= $form->field($model, 'role')->dropDownList(Role::getRoles(),['prompt' => 'בחר תפקיד']) ?>   
	
	

    
	<?= $form->field($model, 'Percent_of_jobs')->dropDownList(PercentOfJobs::getPercentOfJobss(),['prompt' => 'בחר אחוז משרה']) ?>
    
	<?= $form->field($model, 'armed')->dropDownList(Armed::getArmeds(),['prompt' => 'בחר סוג נשק']) ?> 

	
   <?= $form->field($model, 'cellphone')->textInput() ?>

    <?= $form->field($model, 'adress')->textInput(['maxlength' => true]) ?>
	
	
	
	<?= $form->field($model, 'color')->widget(ColorInput::classname(), [
    'options' => ['placeholder' => 'Select color ...'],
])?>


	
	
<!--	< /*?= $form->field($model, 'files[]')->widget(FileInput::classname(), [
	
    'options' => [
	'accept' => 'image/*',
	'multiple' => true,
	
	],
	 'pluginOptions' => [
	 'multiple' => true,
        'browseClass' => 'btn btn-info',
        'browseIcon' => '<i style = "margin-left:5%;" class="glyphicon glyphicon-paperclip"></i> ',
        'browseLabel' =>  'העלה קבצי עובד',
		'removeLabel' =>  'הסר קובץ',
		 'showUpload' => false,
		 'direction' => 'ltr',
    ],
]); ?>-->

   <?= $form->field($model, 'image')->fileInput() ?> 
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'צור עובד' : 'עדכון', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/employees/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmployeesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'role') ?>

    <?= $form->field($model, 'Percent_of_jobs') ?>

    <?php // echo $form->field($model, 'cellphone') ?>

    <?php // echo $form->field($model, 'adress') ?>

    <?php // echo $form->field($model, 'armed') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/employees/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = 'יצירת עובד';
$this->params['breadcrumbs'][] = ['label' => 'עובדים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/employees/files.php
<?php 
use kartik\widgets\FileInput;
 use yii\helpers\Url;
 use yii\helpers\Html;

echo '<h2 align = "center">מסמכים '."$model->fullname".'</h2>'
?>
<?= Html::a('חזור לפרטי עובד', ['view', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
<hr>
<?php
echo '<label class="control-label">הוסף מסמכים</label>';
echo FileInput::widget([
    'model' => $model,
    'name' => 'ImageManager[attachment]',
    'options' => ['multiple' => true,'overwriteInitial '=>false],
	 'pluginOptions' => [
		
		'uploadUrl' => \yii\helpers\Url::to(['/employees/upload-files']),
		'browseIcon' => '<i style = "margin-left:5%;" class="glyphicon glyphicon-paperclip"></i> ',
        'browseLabel' =>  'בחר קבצים',
		'removeLabel' =>  'מחק קבצים',
		'uploadLabel' => 'העלה קבצים',
		'uploadExtraData' => [
            'ImageManager[item_id]' => $model->id  
        ],
		'initialPreview'=>[
            "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/631px-FullMoon2010.jpg",
            "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg"
        ],
        'initialPreviewAsData'=>true,
        'initialCaption'=>"The Moon and the Earth",
        'initialPreviewConfig' => [
            ['caption' => 'Moon.jpg', 'size' => '873727'],
            ['caption' => 'Earth.jpg', 'size' => '1287883'],
        ],
        'overwriteInitial'=>false,
        'maxFileCount' => 30
	],
]);
 

//echo "$model->fullname"
?>

app/views/employees/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EmployeesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'עובדים';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('צור עובד חדש', ['create'], ['class' => 'btn btn-success']) ?>
		<?= Html::a('המרה לאקסל', ['export'], ['class' => 'btn btn-info']) ?>
		
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'id',
            'first_name',
            'last_name',
			'cellphone',
			'email',

			
			[
				'attribute' => 'role',
				'label' => 'תפקיד',
				'format' => 'raw',
				'value' => function($model){
					return $model->roleItem->name;
				},
				'filter'=>Html::dropDownList('EmployeesSearch[role]', $role, $roles, ['class'=>'form-control']),
			],			
			
			
				//'Percent_of_jobs',
           [
				'attribute' => 'Percent_of_jobs',
				'label' => 'אחוז משרה',
				'format' => 'raw',
				'value' => function($model){
					return $model->percent_of_jobsItem->name;
				},
				'filter'=>Html::dropDownList('EmployeesSearch[Percent_of_jobs]', $Percent_of_jobs, $PercentOfJobss, ['class'=>'form-control']),
			],		
		   
		   
           // 'armed',
			[
				'attribute' => 'armed',
				'label' => 'נשק',
				'format' => 'raw',
				'value' => function($model){
					return $model->armedItem->name;
				},
				'filter'=>Html::dropDownList('EmployeesSearch[armed]', $armed, $armeds, ['class'=>'form-control']),
			],			
 
            'adress',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

app/views/employees/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = 'עדכון עובד: ' . $model->fullname;
$this->params['breadcrumbs'][] = ['label' => 'עובדים', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->fullname, 'url' => ['view', 'name' => $model->id]];
$this->params['breadcrumbs'][] = 'עדכון';
?>
<div class="employees-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/employees/upload.php
<?= \kato\DropZone::widget([
       'options' => [
			'url' => 'index.php?r=employees/upload',
           'maxFilesize' => '2',
       ],
       'clientEvents' => [
           'complete' => "function(file){console.log(file)}",
           'removedfile' => "function(file){alert(file.name + ' is removed')}"
       ],
   ]);
   
?>

app/views/employees/view.php
<script>
      function printContent(el)
      {
         var restorepage = document.body.innerHTML;
         var printcontent = document.getElementById(el).innerHTML;
         document.body.innerHTML = printcontent;
         window.print();
         document.body.innerHTML = restorepage;
     }
   </script>
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\bootstrap\Modal;
use yii\web\JsExpression;
use yii\helpers\Url;
use metalguardian\Fotorama;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use kartik\spinner\Spinner;
/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = $model->fullname;
$this->params['breadcrumbs'][] = ['label' => 'עובדים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

 
$this->registerJs("$(function() {
   $('#popupModal').click(function(e) {
     e.preventDefault();
     $('#modal').modal('show').find('.modal-content')
     .load($(this).attr('href'));
   });
});");


    yii\bootstrap\Modal::begin([
	    'header' => '<h2>תמונת עובד</h2>',
		'id' =>'modal',
	
		]);
		
		echo '<button style="margin-left:1%" onclick="printContent("imgemployee");" class = "btn btn-success active">הורד תמונה</button>';
		echo '<button class = "btn btn-default active">הדפס תמונה</button>';
		echo '<hr>';
		echo '<div align="center">';
		echo '<img id="imgemployee" src = "http://localhost/app/web/Employees_images'.'/' .$model->image.'" >';
		echo '</div>';
		
    yii\bootstrap\Modal::end();
	
	

?>
<div class="employees-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
		

		
        <?= Html::a('עדכון', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('מחיקה', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
		<?= Html::a('מסמכי עובד', ['files', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    </p>
	
	
	
<!--<img style= "weight:100px; height:100px;" src="web/uploads/רם.jpg "></img>-->
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'last_name',
			'color',
           
			
			[ // the role name 
				'label' => $model->attributeLabels()['role'],
				'value' => $model->roleItem->name,	
			],			
			
          
			 //'Percent_of_jobs',
			[ // the Percent_of_jobs name 
				'label' => $model->attributeLabels()['Percent_of_jobs'],
				'value' => $model->percent_of_jobsItem->name,	
			],	
			[ // the armed name 
				'label' => $model->attributeLabels()['armed'],
				'value' => $model->armedItem->name,	
			],	
			'email',
            'cellphone',
            'adress',
           			
			/*[
				'attribute' => 'color',
				'value' => 'colorInput::classname()',
				//'format' => ['color', ['width' => '100', 'height'=> '100']],
				
			],*/
			
				
			[
				'attribute' => 'image',
				
				//'value' => Html:: a('http://localhost/project_04.05.17/masterproject/web/uploads'.'/' .$model->image,['http://localhost/project_04.05.17/masterproject/web/uploads'.'/' .$model->image]),
				'value' => 'http://localhost/app/web/Employees_images'.'/' .$model->image,
				'format' => ['image', ['width' => '100','onClick' => 'function myFunction()','id' => 'popupModal', 'class' => 'btn', 'height'=> '100']]
			
			],
		
        ],
    ]) 
	
	
?>
	
<div align = "center;">
<h2>מסמכי עובד:</h2>
<?php
   
		$fotorama = \metalguardian\fotorama\Fotorama::begin(
        [
            'options' => [
                'loop' => true,
                'hash' => true,
                'ratio' => 800/600,
            ],
            'spinner' => [
                'lines' => 20,
            ],
            'tagName' => 'span',
            'useHtmlData' => false,
            'htmlOptions' => [
                'class' => 'custom-class',
                'id' => 'custom-id',
            ],
        ]
    );
	 $TestModel = \app\models\ImageManager::find()->all();
     foreach($TestModel as $one)
	 //for($r = 0; $r < sizeof($model->files); $r++)
	{
		echo Html::img('@web/Employees_files/'.$one->name);
		//echo Html::img('/Employees_files/'.$one->name);
	}
   $fotorama->end();
     ?>
	 
		
</div>
</div>